config/routes.rb
SdSquared::Application.routes.draw do
  resources :secret_code
  devise_for :users, :controllers => {:registrations => "registrations"}
  root  "home#index"

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability


  def initialize(user)

    puts "======================================="
    puts user.inspect
    puts user.roles.map(&:name)
    puts "======================================="

    user ||=User.new #guest user
    roles=[]

    debugger
    user.roles.each do |role|
      if (role.name ==  "admin")
        can [:manage], SecretCodes
      end
    end

  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :user_role_maps, :class_name => "UserRoleMap"
  has_many :users, :class_name => "User", :through => :user_role_maps

end

app/models/secret_codes.rb
class SecretCodes < ActiveRecord::Base
	belongs_to :user

	require "securerandom"

	COUNT_OPTIONS = [1,10,20,50,100]

	def self.create_codes count
		codes = []
		count.times.each do |i|
			code = SecureRandom.uuid[0...6] 
			codes << SecretCodes.create(code: code)
		end
		codes
  end

  def assign_user_to_security_code user_id
    self.user_id = user_id
    self.save!
  end

  scope :available,->{where("user_id is NUll")}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_one :secret_code, class_name: "SecretCodes"
  has_many :user_role_maps, :class_name => "UserRoleMap", :primary_key => :id, :foreign_key => "user_id"
  has_many :roles, :through => :user_role_maps

  def self.current_user
    Thread.current[:current_user]
  end

  def self.current_user= user
    Thread.current[:current_user] = user
  end
end

app/models/user_role_map.rb
class UserRoleMap < ActiveRecord::Base

  belongs_to :user, :class_name => "User"
  belongs_to :role, :class_name => "Role"

  validates_presence_of :role_id, :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  #around_filter :wrap_in_transaction
  before_filter :authenticate_user! , unless: :devise_controller?

  before_filter :clear_thread_context
  before_filter :set_thread_context

  def wrap_in_transaction
    begin
      ActiveRecord::Base.transaction do
        yield
      end
    rescue ActiveRecord::RecordNotFound => e
      message="Your query fetched no results. " + e.message
      flash.now[:error]= message
      @error = message
      log_error e
      render '/home/index'
    rescue ActiveRecord::RecordNotUnique => e
      message="Duplicate Data entered! "
      flash.now[:error] = message + e.message
      @error = message
      log_error e
      render '/home/index'
    rescue ActiveRecord::ActiveRecordError => e
      message="Record Not Found : " + e.message
      flash.now[:error]= message
      @error = message
      log_error e
      render '/home/index'
    rescue NoMethodError => e
      message="Attempt to access a page that does not exist. " + e.message
      flash.now[:error]= message
      @error = message
      log_error e
      render '/home/index'
    rescue ActionView::Template::Error => e
      message="Some error occurred while loading the page. "+ e.message
      flash.now[:error]= message
      @error = message
      log_error e
      render '/home/index'
    rescue Exception => e
      message = "Technical Error! " + e.message
      @error = message
      flash.now[:error] = message
      log_error e
      render '/home/index'
    end
  end


  def clear_thread_context
    Thread.current[:current_user] = nil
  end

  def set_thread_context
    return if ['confirmations', 'sessions', 'registrations', 'passwords'].include? self.controller_name

    if user_signed_in?
      User.current_user= current_user

      puts "======================================="
      puts current_user.roles.map(&:name)
      puts "======================================="

    end

  end


  #uncomment this to rescue can can exceptions
  #rescue_from CanCan::AccessDenied do |exception|
  #  redirect_to root_url, :alert => exception.message
  #end



  protected
    def authenticate_user!
      if user_signed_in?
        super
      else
        flash[:error] = "Please Log in first!"
        redirect_to :new_user_session
      end
    end

    def log_error e
      logger.error "Error" + e.message
      e.backtrace.each do |line|
        logger.error line
      end
    end
    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first,:last, :email, :password) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first,:last, :email, :password, :current_password, :is_female, :date_of_birth) }
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    offset = rand(SecretCodes.available.count)
    @secret_code = SecretCodes.available.offset(offset).first
    if @secret_code.present?
      super
    else
      flash[:error] = "Please request for secret code generation to admin user"
      redirect_to :back
    end

  end

  def create
    if params[:user][:secret_code] != params[:user][:actual_secret_code]
      flash[:error] =  "please enter correct security code"
      redirect_to :back
    else
      super
      email_id = params[:user][:email]
      created_user = User.where(:email=> email_id).first
      sc = SecretCodes.find_by_code params[:user][:actual_secret_code]
      if created_user.present? && sc.present?
          sc.assign_user_to_security_code(created_user.id)
      else
        raise ActiveRecord::Rollback, "Some error occurred. Please try again!"
      end

    end
  end

  def update
    super
  end
end

app/controllers/secret_code_controller.rb
class SecretCodeController < ApplicationController
  load_and_authorize_resource :class => "SecretCodes"

  #show all secrets codes
  #scope-> action handling
  def index
    	@secret_codes = SecretCodes.includes(:user).all
	end

	def create
		strong_params = secret_code_params
		SecretCodes.create_codes strong_params[:count].to_i
		flash[:now] = strong_params[:count]+" secret code created successfully"
		redirect_to :back
	end	

	private
	
	def secret_code_params
    	params.permit(:count)
 	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div>
<h1>Sd Squared home page</h1>

  <% if can? :manage,SecretCodes %>
      <div>
        <%= link_to "Manage Secret Codes", secret_code_index_path,class: "btn btn-success" %>

      </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SdSquared</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div style="margin: 30px">
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
<% flash.each do |name, msg| %> 
<%= content_tag :div, msg, :id => "flash_#{name}" %>
 <% end %>

<%= yield %>
	
</div>

</body>
</html>

app/views/secret_code/index.html.erb
<h1> Secret Codes</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Code</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @secret_codes.each do |sc| %>
      <tr>
        <td><%= sc.code %></td>
        <td><%= sc.user.present? ? sc.user.email : ''  %></td>
        <!-- <td><%#= sc.user.email %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>  

</br>
</br>
</br>
<div class="my-form-group">

  <%= form_tag({:controller => 'secret_code', :action => 'create'}, :method => "post",id: "secret_code_id") do %>
            <div class=" row  my-form-group " >
              <label class="my-control-label" for="inputNormal"> Create Secret Codes :  </label>
              <%= select_tag "count", options_for_select(SecretCodes::COUNT_OPTIONS,10) %>
              <%= submit_tag 'create' ,class: "btn btn-success btn-confirm btn-action "%>
            </div>
  <% end -%>
</div>